### ISSUE TITLE
to Euler Angles

### ISSUE THREAD

**Issue by jniclas** [tomstewart89/Geometry#2]
If we have an indentity matrix and get the euler angles, theta is set to -90°.
The method does not cover the case if (*this)(2,0) is 0. In this case the method executes the last else case that should only executed if (*this)(2,0) is 1. The first if statement should be changed. ?! 

`Matrix<3,2> Rotation::ToEulerAngles()
{
    Matrix<3,2> ret;

    if((*this)(2,0) != 0)
    {
        ret(1,0) = -asin((*this)(2,0));
        ret(1,1) = M_PI - ret(1,0);

        ret(0,0) = atan2((*this)(2,1) / cos(ret(1,0)),(*this)(2,2) / cos(ret(1,0)));
        ret(0,1) = atan2((*this)(2,1) / cos(ret(1,1)),(*this)(2,2) / cos(ret(1,1)));

        ret(2,0) = atan2((*this)(1,0) / cos(ret(1,0)),(*this)(0,0) / cos(ret(1,0)));
        ret(2,1) = atan2((*this)(1,0) / cos(ret(1,1)),(*this)(0,0) / cos(ret(1,1)));
    }
    else
    {
        ret(2,0) = ret(2,1) = 0;

        if((*this)(2,0) == -1)
        {
            ret(1,0) = ret(1,1) = M_PI_2;
            ret(0,0) = ret(0,1) = atan2((*this)(0,1),(*this)(0,2));
        }
        else
        {
            ret(1,0) = ret(1,1) = -M_PI_2;
            ret(0,0) = ret(0,1) = atan2(-(*this)(0,1),-(*this)(0,2));
        }
    }

    return ret;
}`

**Comment by tomstewart89** [comment]
Hi jniclas,

Thanks for the heads up, you're quite right. I'll put up a fix for this on the weekend. In the meantime, feel free to PR if you think you can beat me to it!

**Comment by tomstewart89** [comment]
Well, it only took 3 years, but this problem has been fixed with the overhaul of the euler angle conversion logic I made in v2.0. I added a unit test for exactly this situation in [this commit](https://github.com/tomstewart89/Geometry/commit/82530bd0b3368ffc64cadc2c01ba284d624534ac), so I'll close this issue, thanks again!
