### ISSUE TITLE
Is it LHS or RHS coordinate system?

### ISSUE THREAD

**Issue by funwey** [tomstewart89/Geometry#3]
Hi Tom;

Would like to know if the frame coordinate you are using for the 3D geometry code is left- or right-handed? I know Microsft's DirectX 3D transformations are based on the LHS coordinate.

Rgds

Fun Wey

**Comment by tomstewart89** [comment]
Hey @funwey,

Sorry about the super slow reply, I'm not sure whether you'd still be interested in the answer here but for posterity everything in this library is based on a right-handed coordinate system; I'm a robotics guys and that's just how we operate :mechanical_arm:
