### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by grassjelly** [tomstewart89/Geometry#4]
Hi Tom,

Thanks for this great library. I'm currently tinkering with it and just wondering what's the license for the software? 

Cheers!

**Comment by tomstewart89** [comment]
Hey Juan,

Thanks! I'm glad you're finding it useful. Yeah I've been a bit lazy in defining licenses for my repos. I'll put up an MIT licence for this in a moment so feel free to use this library however you like.

Enjoy!

**Comment by grassjelly** [comment]
Thank you!
