### ISSUE TITLE
Transformation print method does not print Point

### ISSUE THREAD

**Issue by jeromecube44** [tomstewart89/Geometry#7]
Line 256, the erroneous extra `j` parameter in `p(i,j)` causes Point `p` to print as `{0, 0, 0}` when printing a Transformation. Removing it resolves the issue:

Replace line 256
`strm << ((i == 3)? 1 : obj.p(i,j));`
with
`strm << ((i == 3)? 1 : obj.p(i));`

**Comment by tomstewart89** [comment]
Hey @jeromecube44, Thanks for the info and sorry about the incredibly slow reply!  I've been giving this library long overdue attention recently and I'm pretty sure this issue has been fixed in v2.0. If you have any other trouble with this or anything else in v2.0 feel free to open a fresh issue!
